//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy_Zoo.Localization.Interface.MainWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazy_Zoo.Localization.Interface.MainWindow.MainWindowLoc", typeof(MainWindowLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNewBut {
            get {
                return ResourceManager.GetString("AddNewBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AnimalName {
            get {
                return ResourceManager.GetString("AnimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string AnimalSpecies {
            get {
                return ResourceManager.GetString("AnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy Action!.
        /// </summary>
        public static string CrazyActionBut {
            get {
                return ResourceManager.GetString("CrazyActionBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBut {
            get {
                return ResourceManager.GetString("DeleteBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed animal.
        /// </summary>
        public static string FeedAnimalBut {
            get {
                return ResourceManager.GetString("FeedAnimalBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOM TO &quot;CRAZY ZOO&quot;.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string VoiceBut {
            get {
                return ResourceManager.GetString("VoiceBut", resourceCulture);
            }
        }
    }
}
