//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy_Zoo.Usables.Localization.CodeLocalization.MainCodeLoc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazy_Zoo.Usables.Localization.CodeLocalization.MainCodeLoc.MainLoc", typeof(MainLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        public static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird.
        /// </summary>
        public static string Bird {
            get {
                return ResourceManager.GetString("Bird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choco.
        /// </summary>
        public static string Choco {
            get {
                return ResourceManager.GetString("Choco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        public static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony.
        /// </summary>
        public static string Colony {
            get {
                return ResourceManager.GetString("Colony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        public static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        public static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay.
        /// </summary>
        public static string Hay {
            get {
                return ResourceManager.GetString("Hay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat.
        /// </summary>
        public static string Meat {
            get {
                return ResourceManager.GetString("Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but smarter.
        /// </summary>
        public static string MonkeyAddButSmarter {
            get {
                return ResourceManager.GetString("MonkeyAddButSmarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next level cost.
        /// </summary>
        public static string NextLevelCost {
            get {
                return ResourceManager.GetString("NextLevelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO-DIAL-FOUND.
        /// </summary>
        public static string NoDialFound {
            get {
                return ResourceManager.GetString("NoDialFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO-NAME-FOUND.
        /// </summary>
        public static string NoNameFound {
            get {
                return ResourceManager.GetString("NoNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO-SPECIE-FOUND.
        /// </summary>
        public static string NoSpecieFound {
            get {
                return ResourceManager.GetString("NoSpecieFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This animal is chill.
        /// </summary>
        public static string ThisAnimalIsChill {
            get {
                return ResourceManager.GetString("ThisAnimalIsChill", resourceCulture);
            }
        }
    }
}
