//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crazy_Zoo.Usables.Localization.CodeLocalization.AnimalCodeLoc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crazy_Zoo.Usables.Localization.CodeLocalization.AnimalCodeLoc.AnimalLoc", typeof(AnimalLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} absorbing {1} through its cell membrane.
        /// </summary>
        public static string BacteriaEating {
            get {
                return ResourceManager.GetString("BacteriaEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} multiplying rapidly, but still hardly seen.
        /// </summary>
        public static string BacteriaIntro {
            get {
                return ResourceManager.GetString("BacteriaIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacteria.
        /// </summary>
        public static string BacteriaName {
            get {
                return ResourceManager.GetString("BacteriaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prokaryote.
        /// </summary>
        public static string BacteriaSpecie {
            get {
                return ResourceManager.GetString("BacteriaSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .....
        /// </summary>
        public static string BacteriaVoice {
            get {
                return ResourceManager.GetString("BacteriaVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dives like a needle for {1}.
        /// </summary>
        public static string BirdEating {
            get {
                return ResourceManager.GetString("BirdEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot even fly longer than 3 seconds \nin his cage.
        /// </summary>
        public static string BirdFlyAction {
            get {
                return ResourceManager.GetString("BirdFlyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cutting the very sky.
        /// </summary>
        public static string BirdIntro {
            get {
                return ResourceManager.GetString("BirdIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} trying to devour {1} mercilessly.
        /// </summary>
        public static string FishEating {
            get {
                return ResourceManager.GetString("FishEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} swimming in fog of lenses.
        /// </summary>
        public static string FishIntro {
            get {
                return ResourceManager.GetString("FishIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} waiting for something to happen.
        /// </summary>
        public static string FishSwimAction {
            get {
                return ResourceManager.GetString("FishSwimAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} biting juicy {1}.
        /// </summary>
        public static string GroundEating {
            get {
                return ResourceManager.GetString("GroundEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} furyously running in his cage.
        /// </summary>
        public static string GroundIntro {
            get {
                return ResourceManager.GetString("GroundIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} walking in circles.
        /// </summary>
        public static string GroundRunAction {
            get {
                return ResourceManager.GetString("GroundRunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} so hungry, it could eat a {1}....
        /// </summary>
        public static string HorseEating {
            get {
                return ResourceManager.GetString("HorseEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gracefully shakes the earth.
        /// </summary>
        public static string HorseIntro {
            get {
                return ResourceManager.GetString("HorseIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        public static string HorseName {
            get {
                return ResourceManager.GetString("HorseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} so fast, you cannot even see its legs.
        /// </summary>
        public static string HorseRunActin {
            get {
                return ResourceManager.GetString("HorseRunActin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standart horse.
        /// </summary>
        public static string HorseSpecie {
            get {
                return ResourceManager.GetString("HorseSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brrrr.
        /// </summary>
        public static string HorseVoice {
            get {
                return ResourceManager.GetString("HorseVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dont want to eat {1} from the floor.
        /// </summary>
        public static string HumanEating {
            get {
                return ResourceManager.GetString("HumanEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reading papers.
        /// </summary>
        public static string HumanIntro {
            get {
                return ResourceManager.GetString("HumanIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is doing cardio.
        /// </summary>
        public static string HumanRunAction {
            get {
                return ResourceManager.GetString("HumanRunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string HumanSpecie {
            get {
                return ResourceManager.GetString("HumanSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;I wont make sound for you, do you think im some sort of animal?&apos;.
        /// </summary>
        public static string HumanVoice {
            get {
                return ResourceManager.GetString("HumanVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} destroying {1} before eating.
        /// </summary>
        public static string MonkeyEating {
            get {
                return ResourceManager.GetString("MonkeyEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} jumping from tree to tree.
        /// </summary>
        public static string MonkeyIntro {
            get {
                return ResourceManager.GetString("MonkeyIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        public static string MonkeyName {
            get {
                return ResourceManager.GetString("MonkeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} running in his cage, like nothing matters.
        /// </summary>
        public static string MonkeyRunAction {
            get {
                return ResourceManager.GetString("MonkeyRunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primate.
        /// </summary>
        public static string MonkeySpecie {
            get {
                return ResourceManager.GetString("MonkeySpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou, ou, ou.
        /// </summary>
        public static string MonkeyVoice {
            get {
                return ResourceManager.GetString("MonkeyVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} eats {1} slowly.
        /// </summary>
        public static string SnailEats {
            get {
                return ResourceManager.GetString("SnailEats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gracefully glides over the leaves.
        /// </summary>
        public static string SnailIntro {
            get {
                return ResourceManager.GetString("SnailIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob.
        /// </summary>
        public static string SnailName {
            get {
                return ResourceManager.GetString("SnailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hurries with all his might.
        /// </summary>
        public static string SnailRunAction {
            get {
                return ResourceManager.GetString("SnailRunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mollusk.
        /// </summary>
        public static string SnailSpecie {
            get {
                return ResourceManager.GetString("SnailSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string SnailVoice {
            get {
                return ResourceManager.GetString("SnailVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such powerful creature as {0} doesn&apos;t need any {1}.
        /// </summary>
        public static string VirusEating {
            get {
                return ResourceManager.GetString("VirusEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} waiting for his hour to conquer the world.
        /// </summary>
        public static string VirusIntro {
            get {
                return ResourceManager.GetString("VirusIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string VirusName {
            get {
                return ResourceManager.GetString("VirusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} moves in microscopic scale.
        /// </summary>
        public static string VirusRunAction {
            get {
                return ResourceManager.GetString("VirusRunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virus.
        /// </summary>
        public static string VirusSpecie {
            get {
                return ResourceManager.GetString("VirusSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string VirusVoice {
            get {
                return ResourceManager.GetString("VirusVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sucking on tasty {1}.
        /// </summary>
        public static string WormEating {
            get {
                return ResourceManager.GetString("WormEating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wiggling like a worm in a jar.
        /// </summary>
        public static string WormIntro {
            get {
                return ResourceManager.GetString("WormIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} too weak to even say {1}.
        /// </summary>
        public static string WormSound {
            get {
                return ResourceManager.GetString("WormSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} watches you warily.
        /// </summary>
        public static string ZebraIntro {
            get {
                return ResourceManager.GetString("ZebraIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebra.
        /// </summary>
        public static string ZebraName {
            get {
                return ResourceManager.GetString("ZebraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} runs playfully with others.
        /// </summary>
        public static string ZebraRunAction {
            get {
                return ResourceManager.GetString("ZebraRunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plains Zebra.
        /// </summary>
        public static string ZebraSpecie {
            get {
                return ResourceManager.GetString("ZebraSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hufff.
        /// </summary>
        public static string ZebraVoice {
            get {
                return ResourceManager.GetString("ZebraVoice", resourceCulture);
            }
        }
    }
}
